package com.QLKQHT.view;

import com.QLKQHT.dao.TaiKhoanDao;
import java.awt.Image;
import javax.swing.*;
import java.awt.Toolkit;

public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
    	setIconImage(Toolkit.getDefaultToolkit().getImage(LoginFrame.class.getResource("/images/logo-haui.png")));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jCheckBox1 = new javax.swing.JCheckBox();
        MainPanel = new javax.swing.JPanel();
        Panel = new javax.swing.JPanel();
        Logo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        User = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTK = new javax.swing.JTextField();
        Password = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMK = new javax.swing.JPasswordField();
        LogIn = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        PanelSchoolName = new javax.swing.JPanel();
        SchoolName = new javax.swing.JLabel();
        jSeparator = new javax.swing.JSeparator();
        PanelError = new javax.swing.JPanel();
        ErrorMessage = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập");
        setBackground(new java.awt.Color(255, 255, 255));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setMinimumSize(new java.awt.Dimension(500, 500));
        MainPanel.setName(""); // NOI18N
        MainPanel.setPreferredSize(new java.awt.Dimension(500, 500));
        MainPanel.setLayout(new java.awt.GridBagLayout());

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setForeground(new java.awt.Color(255, 255, 255));
        Panel.setMinimumSize(new java.awt.Dimension(500, 450));

        Logo.setBackground(new java.awt.Color(255, 255, 255));
        Logo.setLayout(new javax.swing.BoxLayout(Logo, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/images/logo.jpg")).getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH)));
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(120, 120));
        jLabel1.setMinimumSize(new java.awt.Dimension(120, 120));
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 120));
        Logo.add(jLabel1);

        User.setBackground(new java.awt.Color(255, 255, 255));
        User.setMinimumSize(new java.awt.Dimension(420, 40));
        User.setLayout(new java.awt.GridLayout(2, 1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Tài khoản");
        jLabel2.setMaximumSize(new java.awt.Dimension(120, 40));
        jLabel2.setMinimumSize(new java.awt.Dimension(120, 40));
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 40));
        User.add(jLabel2);

        txtTK.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtTK.setMinimumSize(new java.awt.Dimension(200, 40));
        txtTK.setPreferredSize(new java.awt.Dimension(300, 40));
        txtTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTKMouseClicked(evt);
            }
        });
        User.add(txtTK);

        Password.setBackground(new java.awt.Color(255, 255, 255));
        Password.setMinimumSize(new java.awt.Dimension(420, 40));
        Password.setLayout(new java.awt.GridLayout(2, 1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Mật khẩu");
        jLabel3.setMaximumSize(new java.awt.Dimension(120, 40));
        jLabel3.setMinimumSize(new java.awt.Dimension(120, 40));
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 40));
        Password.add(jLabel3);

        txtMK.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtMK.setMinimumSize(new java.awt.Dimension(200, 40));
        txtMK.setPreferredSize(new java.awt.Dimension(300, 40));
        txtMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMKMouseClicked(evt);
            }
        });
        Password.add(txtMK);

        LogIn.setBackground(new java.awt.Color(255, 255, 255));
        LogIn.setLayout(new javax.swing.BoxLayout(LogIn, javax.swing.BoxLayout.Y_AXIS));

        btnLogin.setBackground(new java.awt.Color(0, 102, 255));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Đăng nhập");
        btnLogin.setAlignmentX(0.5F);
        btnLogin.setBorder(null);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setMaximumSize(new java.awt.Dimension(120, 40));
        btnLogin.setMinimumSize(new java.awt.Dimension(120, 40));
        btnLogin.setPreferredSize(new java.awt.Dimension(120, 40));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        LogIn.add(btnLogin);

        PanelSchoolName.setBackground(new java.awt.Color(255, 255, 255));
        PanelSchoolName.setLayout(new javax.swing.BoxLayout(PanelSchoolName, javax.swing.BoxLayout.PAGE_AXIS));

        SchoolName.setBackground(new java.awt.Color(255, 255, 255));
        SchoolName.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        SchoolName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SchoolName.setText("Trường Đại học Công nghiệp Hà Nội");
        SchoolName.setAlignmentX(0.5F);
        SchoolName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SchoolName.setMaximumSize(new java.awt.Dimension(300, 50));
        SchoolName.setMinimumSize(new java.awt.Dimension(300, 50));
        SchoolName.setPreferredSize(new java.awt.Dimension(300, 50));
        PanelSchoolName.add(SchoolName);

        jSeparator.setMaximumSize(new java.awt.Dimension(350, 10));
        PanelSchoolName.add(jSeparator);

        PanelError.setBackground(new java.awt.Color(255, 255, 255));

        ErrorMessage.setBackground(new java.awt.Color(255, 255, 255));
        ErrorMessage.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        ErrorMessage.setForeground(new java.awt.Color(255, 51, 51));
        ErrorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelError.add(ErrorMessage);

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(LogIn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelSchoolName, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                        .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelSchoolName, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelError, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        MainPanel.add(Panel, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 461, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String tk = String.valueOf(txtTK.getText().trim());
        String mk = String.valueOf(txtMK.getPassword());
        
        if(tk.length() == 0 || mk.length() == 0) {
            ErrorMessage.setText("Tài khoản và mật khẩu không được bỏ trống!");
        }
        else {
            TaiKhoanDao taiKhoan = new TaiKhoanDao();
            String MaTK = taiKhoan.login(tk, mk);
            if(MaTK != null) {
                new HomeFrame(MaTK).setVisible(true);
                this.dispose();
            } else {
                ErrorMessage.setText("Tài khoản hoặc mật khẩu không đúng!");
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMKMouseClicked
        // TODO add your handling code here:
        ErrorMessage.setText("");
    }//GEN-LAST:event_txtMKMouseClicked

    private void txtTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTKMouseClicked
        // TODO add your handling code here:
        ErrorMessage.setText("");
    }//GEN-LAST:event_txtTKMouseClicked
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrorMessage;
    private javax.swing.JPanel LogIn;
    private javax.swing.JPanel Logo;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel Panel;
    private javax.swing.JPanel PanelError;
    private javax.swing.JPanel PanelSchoolName;
    private javax.swing.JPanel Password;
    private javax.swing.JLabel SchoolName;
    private javax.swing.JPanel User;
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JPasswordField txtMK;
    private javax.swing.JTextField txtTK;
    // End of variables declaration//GEN-END:variables
}
